### ISSUE TITLE
vdropzone-removed-file called when dismount the component

### ISSUE THREAD

**Issue by SmartWeb25** [rowanwins/vue-dropzone#85] opened 2017-05-05 18:35 UTC
With the vue-router, using vue-dropzone on one router view. 
After uploading the images and create a object, it redirects to other page. 
Before it, vdropzone-removed-file event called and sends post requests to server to remove all files (those uploaded just before).

**Comment by rowanwins** [comment] 2017-05-06 12:15
Hi @SmartWeb25 

Im a bit confused, are you saying that this is currently occurring, or are you asking that you'd like it to occur?

Thanks

**Comment by SmartWeb25** [comment] 2017-05-08 19:45
Hi @rowanwins 
Sorry for being late. It's currently occurring. I used vdropzone-removed-file event to remove files from server. but since it's called automatically when dismounting the component, the uploaded server files are deleted.

**Comment by rowanwins** [comment] 2017-05-16 11:29
Im going to close this issue as I've resolved it, I'll drop a note when I've published the new version to npm

**Closed by rowanwins** 2017-05-16 11:29 UTC

**Comment by LG0012** [comment] 2017-10-04 11:48
Same problem, any solution?

**Comment by rowanwins** [comment] 2017-10-04 21:44
Hi @LG0012 

What version of vue2-dropzone are you using? Can you please restate the issue in your own language just so Im sure I understand.

**Comment by LG0012** [comment] 2017-10-04 23:34
Hi rowanwins, I'm using the latest vue2-dropzone version. The issue is that
when component is dismonted or for example you are changing the route, the
removed event is firing all the time. And it deletes my all uploaded
images. Right now I solved that issue by cheking the current route, and I
don't like that solution, becouse its smells like hack. Would be nice if
removed event will fire only when then, when im clicking the remove button.
By he way, sorry for my english, i hope you understand, if you want, i can
make a video and show it to you if you want that.

On Oct 5, 2017 00:44, "Rowan Winsemius" <notifications@github.com> wrote:

Hi @LG0012 <https://github.com/lg0012>

What version of vue2-dropzone are you using? Can you please restate the
issue in your own language just so Im sure I understand.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rowanwins/vue-dropzone/issues/85#issuecomment-334298615>,
or mute the thread

**Comment by 1shiharat** [comment] 2017-10-11 08:56
I'm experiencing the same problem ...

**Comment by 1shiharat** [comment] 2017-10-11 09:05
https://github.com/rowanwins/vue-dropzone/blob/vue2/src/index.vue#L396
https://github.com/enyo/dropzone/issues/998#issuecomment-332519839

**Comment by Artem-Schander** [comment] 2017-10-13 08:55
same here - v2.3.6

**Comment by FrancescoMussi** [comment] 2017-10-24 13:05
Same problem here.

Example case:

- I open my EDIT PROPERTY page
- the dropzone is pre-loaded with the existing images using `manuallyAddFile`
- without doing anything, I click on a link a sidebar to go to another page
- the remove event is fired `v-on:vdropzone-removed-file="imageRemoved"`

It resemble an on-blur event.

Please can we fix this somehow?
Or some workaround to avoid this behavior?

**Comment by theromie** [comment] 2018-07-09 12:05
same here - v3.1.0

**Comment by PHPGuus** [comment] 2019-05-21 07:19
You can detect the difference in your `vdropzone-removed-file` handler by checking whether or not the dropzone element is disabled:
```this.$refs.vueDropzone.dropzone.disabled !== true``` means that the user clicked the "Remove file" button.

**Comment by ali-seyfi** [comment] 2020-10-18 05:36
whewn i use `this.$refs.vueDropzone.dropzone.disabled !== true` i get following error

> Uncaught TypeError: Cannot read property 'vueDropzone' of undefined

**Comment by Robin-Hoodie** [comment] 2020-12-07 11:10
@tihootech That's probably because you haven't registered "vueDropzone" as a reference: https://vuejs.org/v2/api/#ref

This is still happening for `3.6.0` btw

**Comment by Robin-Hoodie** [comment] 2020-12-07 11:15
Happy to implement a fix for this @rowanwins 

Seems like this can be fixed by setting a `isDestroying` file in the `beforeDestroy` hook and checking on that here https://github.com/rowanwins/vue-dropzone/blob/c88b8b08922cca4743a7fde03a0213e8c7a34f0f/src/components/vue-dropzone.vue#L136

**Comment by hugorax** [comment] 2021-11-30 21:54
same problem how can I resolve it?
just I need to clean the area dropzone to load new files. is dynamic. 

i use ^3.6.0
