### ISSUE TITLE
not working in IE10,11

### ISSUE THREAD

**Issue by bs06116** [rowanwins/vue-dropzone#453] opened 2019-05-16 07:20 UTC
when i run vue2-dropzone on IE10,11 its not working.even my project not running.can you give me solution.

**Comment by rowanwins** [comment] 2019-05-16 09:47
Hi @bs06116 

I'm guessing it's related to #443 & #439 . There are some suggestions in those issues. If this is a duplicate of those issues can you please close this issue.

Thanks

**Closed** 2019-06-03 06:03 UTC
