### ISSUE TITLE
Pass Product Id in the URL

### ISSUE THREAD

**Issue by bobbygerez** [rowanwins/vue-dropzone#97] opened 2017-05-24 07:28 UTC
I need to pass an Id in the URL. How can I do it?

```
<dropzone id="myVueDropzone" url="../api/photo/product/upload" v-on:vdropzone-success="showSuccess" >
                      <!-- Optional parameters if any! -->
        </dropzone>
```

I need to pass a product ID in the URL or as a Parameters. How ? TY

**Comment by bobbygerez** [comment] 2017-05-24 08:05
I have tried this one but it doesn't work.
```
<template>
    <div>    
      <dropzone id="myVueDropzone" url="https://httpbin.org/post" v-on:vdropzone-sending="sendingEvent"></dropzone>
  </div>
</template>

<script>
  import Dropzone from 'vue2-dropzone'

  export default {
    name: 'MainApp',
    components: {
      Dropzone
    },
    methods: {
      'sendingEvent': function (file, xhr, formData) {
         doSomethingInHere()
      }
    }
  }
</script>
```

**Comment by vrajroham** [comment] 2017-05-24 08:42
have you tried using get parameters in url?

like `https://httpbin.org/post?id=my_id&other_param=value`

**Comment by rowanwins** [comment] 2017-05-24 09:01
Hi @bobbygerez 

You should be able to do something using the sending event and the formData, eg
````
   formData.append('productid', this.someId);
````
I think this would be preferable to the approach proposed by @vrajroham 
Let me know how you get on

**Comment by bobbygerez** [comment] 2017-05-24 09:06
It doesn't actually trigger. Even just a console.log 
```
'sendingEvent': function (file, xhr, formData) {
         			console.log('sample')
     		 }
```

**Comment by bobbygerez** [comment] 2017-05-24 09:07
The success works fine. 

```
showSuccess: function (file) {

		        console.log('A file was successfully uploaded')
		      },
```

**Comment by rowanwins** [comment] 2017-05-24 09:14
Hmmmm that's a bit weird @bobbygerez 

I'm actually without a computer at the moment so I'm not able to assist further just at the moment sorry, hope you can get it resolved

**Comment by bobbygerez** [comment] 2017-05-24 09:18
That is fine @rowanwins . I can wait for 1 or 2 days. Thank you for assisting me... I'm glad you made this.

**Comment by bobbygerez** [comment] 2017-05-26 06:09
For the meantime I will use this first https://github.com/rowanwins/vue-dropzone/issues/44 . This one solve my problem. I hope you can reply to why it's triggering. Thanks...

**Comment by rowanwins** [comment] 2017-06-25 12:48
I've re-tested and confirmed that the `sending` event is indeed firing so Im not sure what's happening for you @bobbygerez . If you're ok with it im going to close this issue because I can't replicate it, feel free to reopen if you can provide any more detail.

**Closed by rowanwins** 2017-06-25 12:48 UTC

**Comment by bobbygerez** [comment] 2017-06-30 06:15
@rowanwins version 2.0.0 in the docs doesn't work but the version 2.3.4 works fine. I hope you can update the docs. Thanks for creating this.
